CREATE TABLE IF NOT EXISTS users (
    userID INTEGER PRIMARY KEY AUTOINCREMENT,
    firstName VARCHAR(50) NOT NULL,
    lastName VARCHAR(50) NOT NULL,
    gender TEXT NOT NULL DEFAULT 'male' CHECK (gender IN ('male','female')),
    birthdate TEXT NOT NULL ,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(50) NOT NULL, 
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);