PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS sessions (
    sessionToken VARCHAR(200) NOT NULL PRIMARY KEY,
    userID  TEXT NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (userID) REFERENCES users(userID) ON DELETE CASCADE
);